language: node_js
node_js:
- '8'
after_success:
- yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
- yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
      secure: "SAx24uhILDPA05bCOMOy7WlA9QlCWa87Em+paAd5tauYR2D8W4uKR7SBMxm1WgpIhgk641hj2fVmfBa4oMp1v4Jfvq7fa4cJzCq3JDmSOoO5yc2Zce260vB6Sa8g6iuBfU4gjIYrCblZNMBCktCMEJgENiVtRdQTb33awMS/XmGV0Xh61FCUnAsuP3RTE+TIWfYLwHL+5Z79TKTGnjP73g/NljWxX0fsxNBjV8GMoH3Qgvjmd1Nga4XolLxj3u4Mj/74fLPtEiILMyiu9/X3X5vBQAkFbqhZ/wr1o2aF4lj7xqgk9LCatg/dUuC2Rk5A8e6VUsuT+4iUYb5MtrWXpltu+LwhdgKaDzKmPAd6Y0H5CcsIlQhGzU82cIeU+faUrECpU1jXQo41ODM0ZhGwZJfUzQLN9OwvABDHBYDbXCA+QvWiy1izGRE0aMGXIhXbw+5AxCWqc61pSVhOWRMQJ8ak219gBpQqNhip3M/ZrklDAiXQXy+vFuD9xpnG0BFzrhyJAwfRKZfHC/vQHRtLTwAmapE38iOauZfZU8Sbc3Q0bNQxNy8loBXcx1ExbIsp52pyaE4OsgwmkQeJITbxxtlNy0uw5EZPoCMdv8jYz9m/vPMzSLoILb3G8RUowQvNt+sHMx+mSt0/4XhnefBS6v5reiRSzdjt/L+VECx1ePA="
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    repo: terascope/error_parser
